# AUTOGENERATED! DO NOT EDIT! File to edit: compat_checker.ipynb.

import ast
from dataclasses import dataclass
from pathlib import Path
from fastcore.script import call_parse

HTMX_V4ONLY_ATTRS = 'action method config ignore'
HTMX_V2ONLY_ATTRS = 'disabled_elt ext history history_elt inherit params prompt request'

HTMX_V4ONLY_EVTS = 'after:init before:cleanup before:history:update before:init before:process before:history:restore after:history:push after:history:replace error'
HTMX_V2ONLY_EVTS = 'afterOnLoad afterProcessNode beforeCleanupElement beforeHistorySave beforeOnLoad beforeProcessNode beforeTransition historyCacheMiss historyRestore load oobAfterSwap oobBeforeSwap pushedIntoHistory replacedInHistory sendError swapError targetError timeout'

def _hx_attr_kwargs(xs): return {f'hx_{x}' for x in xs.split()}
def _hx_evt_kwarg(x): return 'hx_on__' + _camel2snake(x).replace(':', '_')
def _hx_evt_kwargs(xs): return {_hx_evt_kwarg(x) for x in xs.split()}

def _camel2snake(s):
    res = []
    for i,c in enumerate(s):
        if c.isupper() and i and s[i-1] not in ':_': res.append('_')
        res.append(c.lower())
    return ''.join(res)

V4ONLY_KWARGS = _hx_attr_kwargs(HTMX_V4ONLY_ATTRS) | _hx_evt_kwargs(HTMX_V4ONLY_EVTS)
V2ONLY_KWARGS = _hx_attr_kwargs(HTMX_V2ONLY_ATTRS) | _hx_evt_kwargs(HTMX_V2ONLY_EVTS)

@dataclass
class HtmxCompatIssue:
    lineno: int
    col_offset: int
    name: str
    target: int
    message: str

def _const_bool(node):
    return node.value if isinstance(node, ast.Constant) and isinstance(node.value, bool) else None

def _call_name(node):
    if isinstance(node.func, ast.Name): return node.func.id
    if isinstance(node.func, ast.Attribute): return node.func.attr
    return None

def _call_htmx4_kw(node):
    for kw in node.keywords:
        if kw.arg == 'htmx4': return _const_bool(kw.value)
    return False

class HtmxCompatVisitor(ast.NodeVisitor):
    def __init__(self, target=None):
        self.target = target
        self.inferred_versions = []
        self.issues = []

    def visit_Call(self, node):
        name = _call_name(node)
        if name in {'fast_app', 'FastHTML'}:
            htmx4 = _call_htmx4_kw(node)
            if htmx4 is not None: self.inferred_versions.append(4 if htmx4 else 2)
        self._check_keywords(node)
        self.generic_visit(node)

    def _resolved_target(self):
        if self.target in (2,4): return self.target
        versions = set(self.inferred_versions)
        return versions.pop() if len(versions) == 1 else None

    def _check_keywords(self, node):
        target = self._resolved_target()
        if target is None: return
        bad = V2ONLY_KWARGS if target == 4 else V4ONLY_KWARGS
        bad_version = 2 if target == 4 else 4
        for kw in node.keywords:
            if kw.arg is None: continue
            if kw.arg in bad:
                self.issues.append(HtmxCompatIssue(
                    kw.value.lineno,
                    kw.value.col_offset,
                    kw.arg,
                    target,
                    f'{kw.arg} is htmx v{bad_version}-only, but this source targets htmx v{target}.'))

def infer_htmx_version(src):
    "Infer htmx target version from direct fast_app/FastHTML calls, returning 2, 4, or None."
    tree = ast.parse(src)
    visitor = HtmxCompatVisitor()
    visitor.visit(tree)
    versions = set(visitor.inferred_versions)
    return versions.pop() if len(versions) == 1 else None

def check_htmx_compat(src, target=None):
    "Return static compatibility issues for FastHTML htmx kwargs in `src`."
    tree = ast.parse(src)
    visitor = HtmxCompatVisitor(target=target)
    visitor.visit(tree)
    return visitor.issues

def _py_files(path):
    path = Path(path)
    if path.is_file(): return [path]
    return sorted(p for p in path.rglob('*.py') if '.venv' not in p.parts and '__pycache__' not in p.parts)

def check_htmx_compat_path(path, target=None):
    "Return `(path, issue)` pairs for Python files under `path`."
    res = []
    for p in _py_files(path):
        try: src = p.read_text()
        except UnicodeDecodeError: continue
        for issue in check_htmx_compat(src, target=target): res.append((p, issue))
    return res

@call_parse
def htmx_compat_check(
    path:str='.', # File or directory to scan
    target:int=0  # Target htmx version. Use 0 to infer from fast_app/FastHTML calls.
):
    "Check FastHTML source for obvious htmx v2/v4 compatibility issues."
    issues = check_htmx_compat_path(path, target=target or None)
    for p,issue in issues:
        print(f'{p}:{issue.lineno}:{issue.col_offset + 1}: {issue.message}')
    if issues: raise SystemExit(1)
