# AUTOGENERATED! DO NOT EDIT! File to edit: code_editor.ipynb.

# %% auto 0
__all__ = ['css', 'ace_editor', 'app', 'rt', 'js_code', 'example_code', 'CodeEditor', 'get']

# %% code_editor.ipynb 3
from fasthtml import *

css = Style('''\
#editor {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}
''')
# Ace Editor (https://ace.c9.io/)
ace_editor = Script(src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.35.0/ace.min.js")
app = FastHTML(hdrs=(ace_editor, css))
rt = app.route

# %% code_editor.ipynb 4
js_code = """\
var editor = ace.edit("editor");
editor.setTheme("ace/theme/monokai");
editor.session.setMode("ace/mode/javascript");
"""

example_code = """\
function foo(items) {
    var x = "All this is syntax highlighted";
    return x;
}"""

# %% code_editor.ipynb 5
def CodeEditor():
    editor = Div(example_code, id="editor")
    return Title("Code Editor",), editor, Script(NotStr(js_code))

# %% code_editor.ipynb 7
@rt("/")
def get():
    return CodeEditor()
