"""Use FastHTML in Jupyter notebooks

Docs: https://www.fastht.ml/docs/api/jupyter.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/06_jupyter.ipynb.

# %% auto #0
__all__ = ['nb_serve', 'nb_serve_async', 'show', 'render_ft', 'htmx_config_port', 'JupyUvi', 'JupyUviAsync', 'HTMX', 'ws_client']

# %% ../nbs/api/06_jupyter.ipynb #2c69d9d0
import asyncio, time, uvicorn
from threading import Thread
from fastcore.utils import *
from fastcore.meta import delegates
from fastcore.net import wait_port_free, wait_port_free_async
from .common import *
from .common import show as _show
from fastcore.parallel import startthread
try: from IPython.display import HTML,Markdown,display
except ImportError: pass

# %% ../nbs/api/06_jupyter.ipynb #a5d3a8f7
def nb_serve(app, log_level="error", port=8000, host='0.0.0.0', daemon=False, **kwargs):
    "Start a Jupyter compatible uvicorn server with ASGI `app` on `port` with `log_level`; use `daemon=True` for notebook tests so failed runs don't block process shutdown"
    server = uvicorn.Server(uvicorn.Config(app, log_level=log_level, host=host, port=port, **kwargs))
    @startthread(daemon=daemon)
    def run_server(): asyncio.run(server.serve())
    while not server.started: time.sleep(0.01)
    return server

# %% ../nbs/api/06_jupyter.ipynb #3242080c
async def nb_serve_async(app, log_level="error", port=8000, host='0.0.0.0', **kwargs):
    "Async version of `nb_serve`"
    server = uvicorn.Server(uvicorn.Config(app, log_level=log_level, host=host, port=port, **kwargs))
    asyncio.get_running_loop().create_task(server.serve())
    while not server.started: await asyncio.sleep(0.01)
    return server

# %% ../nbs/api/06_jupyter.ipynb #654b36bb
@delegates(_show)
def show(*s, **kwargs):
    "Same as fasthtml.components.show, but also adds `htmx.process()`"
    if IN_NOTEBOOK: return _show(*s, Script('if (window.htmx) htmx.process(document.body)'), **kwargs)
    return _show(*s, **kwargs)

# %% ../nbs/api/06_jupyter.ipynb #6a962b54
def render_ft(**kw):
    "Call once in a notebook or solveit dialog to auto-render components with HTMX support"
    @patch
    def _repr_html_(self:FT):
        scr_proc = Script('if (window.htmx) htmx.process(document.body)')
        return to_xml(Div(self, scr_proc, **kw))

# %% ../nbs/api/06_jupyter.ipynb #1daaa0e1
def htmx_config_port(port=8000, htmx4=False):
    evt = 'htmx-config-request' if htmx4 else 'htmx:configRequest'

    display(HTML(f'''
<script>
document.body.addEventListener('{evt}', (event) => {{
    const path = {'event.detail.ctx.request.action' if htmx4 else 'event.detail.path'};
    if (path.includes('://')) return;

    const full = `${{location.protocol}}//${{location.hostname}}:{port}${{path}}`;

    {'event.detail.ctx.request.mode = "cors";' if htmx4 else 'htmx.config.selfRequestsOnly = false;'}
    {'event.detail.ctx.request.action = full;' if htmx4 else 'event.detail.path = full;'}
}});
</script>'''))


# %% ../nbs/api/06_jupyter.ipynb #79406618
class JupyUvi:
    "Start and stop a Jupyter compatible uvicorn server with ASGI `app` on `port` with `log_level`"
    def __init__(self, app, log_level="error", host='0.0.0.0', port=8000, start=True, live=False, live_rt='/_lr', daemon=False, **kwargs):
        self.kwargs = kwargs
        store_attr(but='start,live')
        self.server = None
        self._live_ver = 0
        if live: self._setup_live(app)
        if start: self.start()
        if not os.environ.get('IN_SOLVEIT'): htmx_config_port(port, htmx4=app.htmx4)

    def start(self):
        self.server = nb_serve(self.app, log_level=self.log_level, host=self.host, port=self.port,daemon=self.daemon, **self.kwargs)

    def stop(self):
        self.server.should_exit = True
        wait_port_free(self.port, self.host)

    def _setup_live(self, app):
        rt = self.live_rt or '/_lr'
        if not rt.startswith('/'): rt = f'/{rt}'
        app.hdrs.append(Script(f"new EventSource({rt!r}).onmessage=e=>{{if(e.data==='reload')navigation.reload()}}"))
        @app.get(rt)
        async def _sse(): return EventStream(self._live_sse())
        get_ipython().events.register('post_run_cell', lambda _: setattr(self, '_live_ver', self._live_ver+1))

    async def _live_sse(self):
        ver = self._live_ver
        while not self.server.should_exit:
            await asyncio.sleep(0.1)
            if ver != self._live_ver:
                ver = self._live_ver
                yield 'data: reload\n\n'

# %% ../nbs/api/06_jupyter.ipynb #f6316c73
class JupyUviAsync(JupyUvi):
    "Start and stop an async Jupyter compatible uvicorn server with ASGI `app` on `port` with `log_level`"
    def __init__(self, app, log_level="error", host='0.0.0.0', port=8000, **kwargs):
        super().__init__(app, log_level=log_level, host=host, port=port, start=False, **kwargs)

    async def start(self):
        self.server = await nb_serve_async(self.app, log_level=self.log_level, host=self.host, port=self.port, **self.kwargs)

    async def stop(self):
        self.server.should_exit = True
        await wait_port_free_async(self.port, self.host)


# %% ../nbs/api/06_jupyter.ipynb #a448e420
from starlette.testclient import TestClient
from html import escape

# %% ../nbs/api/06_jupyter.ipynb #89b8984b
def HTMX(path="/", host='localhost', app=None, port=8000, height="auto", link=False, iframe=True, client=None):
    "An iframe which displays the HTMX application in a notebook."
    if isinstance(height, int): height = f"{height}px"
    scr = """{
        let frame = this;
        window.addEventListener('message', function(e) {
            if (e.source !== frame.contentWindow) return; // Only proceed if the message is from this iframe
            if (e.data.height) frame.style.height = (e.data.height+1) + 'px';
        }, false);
    }""" if height == "auto" else ""
    proto = 'http' if host=='localhost' else 'https'
    fullpath = f"{proto}://{host}:{port}{path}" if host else path
    src = f'src="{fullpath}"'
    if link: display(HTML(f'<a href="{fullpath}" target="_blank">Open in new tab</a>'))
    if isinstance(path, (FT,tuple,Safe)):
        assert app, 'Need an app to render a component'
        route = f'/{unqid()}'
        res = path
        app.get(route)(lambda: res)
        cli = client if client is not None else TestClient(app)
        page = cli.get(route).text
        src = f'srcdoc="{escape(page)}"'
    if iframe:
        return HTML(f'<iframe {src} style="width: 100%; height: {height}; border: none;" onload="{scr}" ' + """allow="accelerometer; autoplay; camera; clipboard-read; clipboard-write; display-capture; encrypted-media; fullscreen; gamepad; geolocation; gyroscope; hid; identity-credentials-get; idle-detection; magnetometer; microphone; midi; payment; picture-in-picture; publickey-credentials-get; screen-wake-lock; serial; usb; web-share; xr-spatial-tracking"></iframe> """)

# %% ../nbs/api/06_jupyter.ipynb #850155aa
def ws_client(app, nm='', host='localhost', port=8000, ws_connect='/ws', frame=True, link=True, **kwargs):
    path = f'/{nm}'
    c = Main('', cls="container", id=unqid())
    @app.get(path)
    def f():
        return Div(c, id=nm or '_dest', hx_trigger='load',
                   hx_ext="ws", ws_connect=ws_connect, **kwargs)
    if link: display(HTML(f'<a href="http://{host}:{port}{path}" target="_blank">open in browser</a>'))
    if frame: display(HTMX(path, host=host, port=port))
    def send(o): asyncio.create_task(app._send(o))
    c.on(send)
    return c
