"""Passwordless auth combining magic links and passkeys"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/10_magickey.ipynb.

# %% auto #0
__all__ = ['MagicKey']

# %% ../nbs/api/10_magickey.ipynb #d3fd43fe
from .common import *
from webauthn import generate_authentication_options, generate_registration_options, verify_authentication_response, verify_registration_response, options_to_json
from webauthn.helpers import base64url_to_bytes, bytes_to_base64url
from webauthn.helpers.structs import AuthenticatorSelectionCriteria, ResidentKeyRequirement, UserVerificationRequirement
from json import loads
import secrets, time

# %% ../nbs/api/10_magickey.ipynb #03d86e44
def _origin_kw(req):
    host = req.url.hostname
    scheme = 'http' if host in ('localhost', '127.0.0.1') else 'https'
    return dict(expected_origin=f'{scheme}://{req.url.netloc}', expected_rp_id=host)

# %% ../nbs/api/10_magickey.ipynb #811449f3
class MagicKey:
    def __init__(self, app, send_email, skip=None, login_path='/login', logout_path='/logout'):
        if not skip: skip = [login_path, '/verify_magiclink', '/send_magic_link', '/request_passkey_auth',
                             '/verify_passkey_auth', '/setup_passkey', '/request_passkey_reg',
                             '/finish_passkey_reg', '/skip_passkey_reg']
        self.magiclink_db = {}
        store_attr()

        async def before(req, session):
            if 'auth' not in req.scope: req.scope['auth'] = session.get('auth')
            if not req.scope['auth']: return RedirectResponse(login_path, status_code=303)
        app.before.append(Beforeware(before, skip=skip))

        @app.get(logout_path)
        def logout(session):
            session.pop('auth', None)
            return RedirectResponse(login_path, status_code=303)

        @app.post('/send_magic_link')
        def send_magic_link(email: str, req):
            token = secrets.token_urlsafe(32)
            self.magiclink_db[token] = dict(email=email, timestamp=time.time(), used=False)
            scheme = 'http' if req.url.hostname in ('localhost', '127.0.0.1') else 'https'
            magic_url = f'{scheme}://{req.url.netloc}/verify_magiclink?token={token}'
            return self.send_email(email, magic_url)

        @app.get('/verify_magiclink')
        def verify_magiclink(token: str, session, req):
            link = self.magiclink_db.get(token)
            if not link or link['used'] or time.time() - link['timestamp'] > 3600: return P('Invalid or expired link')
            link['used'] = True
            return self.after_magiclink_verify(link['email'], session, req)

        @app.post('/request_passkey_auth')
        def request_passkey_auth(session, req):
            auth_opts = generate_authentication_options(
                rp_id=req.url.hostname, user_verification=UserVerificationRequirement.PREFERRED)
            session['auth_challenge'] = bytes_to_base64url(auth_opts.challenge)
            return Script("""
                SimpleWebAuthnBrowser.startAuthentication({ optionsJSON: %s }).then(r => {
                    htmx.ajax('POST', '/verify_passkey_auth', { values: r, target:'#result' });
                });""" % options_to_json(auth_opts))

        @app.post('/verify_passkey_auth')
        def verify_passkey_auth(response: str, id: str, data: dict, session, req):
            challenge = base64url_to_bytes(session.pop('auth_challenge'))
            cred_id = base64url_to_bytes(id)
            stored = self.get_passkey(cred_id)
            if not stored: return P('No matching passkey')
            data['response'] = loads(response)
            res = verify_authentication_response(
                credential_public_key=stored['public_key'], credential_current_sign_count=stored['sign_count'],
                credential=data, expected_challenge=challenge, require_user_verification=True, **_origin_kw(req))
            self.update_passkey(cred_id, res.new_sign_count)
            session['auth'] = stored['email']
            return self._do_auth(stored['email'], session, htmx=True)

        @app.post('/request_passkey_reg')
        def request_passkey_reg(session, req):
            email = session.get('pending_email')
            if not email: return P('No pending registration')
            uid = base64url_to_bytes(email)
            selec = AuthenticatorSelectionCriteria(resident_key=ResidentKeyRequirement.REQUIRED, require_resident_key=True)
            opts = generate_registration_options(
                rp_id=req.url.hostname, rp_name='MagicKey', user_name=email, user_id=uid, authenticator_selection=selec)
            session['reg_challenge'] = bytes_to_base64url(opts.challenge)
            return Script("""
                SimpleWebAuthnBrowser.startRegistration({ optionsJSON: %s }).then(r => {
                    htmx.ajax('POST', '/finish_passkey_reg', { values: r, target:'#result' });
                });""" % options_to_json(opts))

        @app.post('/finish_passkey_reg')
        def finish_passkey_reg(response: str, data: dict, session, req):
            email = session.pop('pending_email', None)
            if not email: return P('No pending registration')
            challenge = base64url_to_bytes(session.pop('reg_challenge'))
            data['response'] = loads(response)
            res = verify_registration_response(
                credential=data, expected_challenge=challenge, require_user_verification=True, **_origin_kw(req))
            self.save_passkey(res.credential_id, email, res.credential_public_key, res.sign_count)
            session['auth'] = email
            return self._do_auth(email, session, htmx=True)

        @app.get('/skip_passkey_reg')
        def skip_passkey_reg(session):
            email = session.pop('pending_email', None)
            if not email: return RedirectResponse(login_path, status_code=303)
            session['auth'] = email
            return self._do_auth(email, session, htmx=False)

    def _do_auth(self, email, session, htmx=False):
        url = self.get_auth(email, session)
        if htmx: return HttpHeader('HX-Redirect', url)
        return RedirectResponse(url, status_code=303)

    def get_auth(self, email, session): raise NotImplementedError()
    def has_passkey(self, email): return False
    def get_passkey(self, credential_id): return None
    def save_passkey(self, credential_id, email, public_key, sign_count): raise NotImplementedError()
    def update_passkey(self, credential_id, sign_count): raise NotImplementedError()

    def after_magiclink_verify(self, email, session, req):
        if self.has_passkey(email):
            session['auth'] = email
            return self._do_auth(email, session, htmx=False)
        session['pending_email'] = email
        return RedirectResponse('/setup_passkey', status_code=303)
