"""Simple token-bucket rate limiting for FastHTML routes"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/07_ratelimit.ipynb.

# %% auto #0
__all__ = ['parse_rate', 'TokenBucket', 'client_ip', 'limiter']

# %% ../nbs/api/07_ratelimit.ipynb #b33aec8a
import re,time
from math import ceil
from typing import Callable
from starlette.responses import Response
from fastcore.utils import *

# %% ../nbs/api/07_ratelimit.ipynb #1078d10b
_units = dict(s=1, m=60, h=3600, d=86400)

def parse_rate(s):
    "Parse rate string like `'5/m'`, `'1 per day'`, `'100/2h'`"
    m = re.match(r'(\d+)\s*(?:/|per)\s*(\d+)?\s*([smhd])', s, re.I)
    if not m: raise ValueError(f"Invalid rate: {s}")
    n,mult,unit = m.groups()
    return int(n), _units[unit.lower()] * int(mult or 1)

# %% ../nbs/api/07_ratelimit.ipynb #7b28079a
class TokenBucket:
    "Token-bucket rate limiter"
    def __init__(self,
                 max_reqs:str|int,     # Rate string ('5/m') or max requests per window
                 window_secs:int=None  # Window in seconds (required if `max_reqs` is int)
                ):
        if window_secs is None: max_reqs,window_secs = parse_rate(max_reqs)
        store_attr()
        self.rate = max_reqs / window_secs
        self.buckets = {}
    def __repr__(self): return f'TokenBucket({self.max_reqs}, {self.window_secs})'

    def _prune(self):
        cutoff = time.time() - self.window_secs
        self.buckets = {k:(t,ts) for k,(t,ts) in self.buckets.items() if ts > cutoff}
    def wait(self, key):
        "Return 0 if allowed, else seconds to wait"
        self._prune()
        now = time.time()
        tokens, last = self.buckets.get(key, (self.max_reqs, now))
        tokens = min(self.max_reqs, tokens + (now - last) * self.rate)
        if tokens < 1: return (1 - tokens) / self.rate
        self.buckets[key] = (tokens - 1, now)
        return 0

# %% ../nbs/api/07_ratelimit.ipynb #5b3c8231
def client_ip(req, **kwargs):
    "Get client IP from `X-Forwarded-For` header (assumes deployment behind a single Caddy reverse proxy)"
    return req.headers.get('x-forwarded-for', '').split(',')[0].strip() or (req.client and req.client.host) or ''

# %% ../nbs/api/07_ratelimit.ipynb #97f054cb
def limiter(rate:str|tuple,             # Rate string ('5/m') or (max_reqs, window_secs) tuple
            key:str|Callable=client_ip, # Key to limit by: route param name, or callable(req, **kwargs)
            on_limit:Callable=None      # Optional callback(wait_secs) to return custom response on 429
    ):          
    "Create a `before` function that rate-limits requests"
    bucket = TokenBucket(*rate) if isinstance(rate, tuple) else TokenBucket(rate)
    def _429(w):
        if on_limit: return on_limit(w)
        return Response('Too many requests', status_code=429, headers={'Retry-After': str(ceil(w))})
    if callable(key):
        def before(req):
            if w:=bucket.wait(key(req)): return _429(w)
        return before
    async def before(req):
        v = ifnone(req.path_params.get(key), req.query_params.get(key))
        if v is None: v = (await req.form()).get(key)
        if w:=bucket.wait(str(v or '')): return _429(w)
    return before
