"""Simple token-bucket rate limiting for FastHTML routes"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/07_ratelimit.ipynb.

# %% auto #0
__all__ = ['parse_rate', 'TokenBucket', 'client_ip', 'Limiter']

# %% ../nbs/api/07_ratelimit.ipynb #b33aec8a
import asyncio,re,time
from contextvars import ContextVar
from functools import wraps
from math import ceil
from typing import Callable
from starlette.responses import Response
from fastcore.utils import *

# %% ../nbs/api/07_ratelimit.ipynb #1078d10b
_units = dict(s=1, m=60, h=3600, d=86400)

def parse_rate(s):
    "Parse rate string like `'5/m'`, `'1 per day'`, `'100/2h'`"
    m = re.match(r'(\d+)\s*(?:/|per)\s*(\d+)?\s*([smhd])', s, re.I)
    if not m: raise ValueError(f"Invalid rate: {s}")
    n,mult,unit = m.groups()
    return int(n), _units[unit.lower()] * int(mult or 1)

# %% ../nbs/api/07_ratelimit.ipynb #7b28079a
class TokenBucket:
    "Token-bucket rate limiter"
    def __init__(self,
                 max_reqs:str|int,     # Rate string ('5/m') or max requests per window
                 window_secs:int=None  # Window in seconds (required if `max_reqs` is int)
                ):
        if window_secs is None: max_reqs,window_secs = parse_rate(max_reqs)
        store_attr()
        self.rate = max_reqs / window_secs
        self.buckets = {}
    def __repr__(self): return f'TokenBucket({self.max_reqs}, {self.window_secs})'

    def _prune(self):
        cutoff = time.time() - self.window_secs
        self.buckets = {k:(t,ts) for k,(t,ts) in self.buckets.items() if ts > cutoff}
    def wait(self, key):
        "Return 0 if allowed, else seconds to wait"
        self._prune()
        now = time.time()
        tokens, last = self.buckets.get(key, (self.max_reqs, now))
        tokens = min(self.max_reqs, tokens + (now - last) * self.rate)
        if tokens < 1: return (1 - tokens) / self.rate
        self.buckets[key] = (tokens - 1, now)
        return 0

# %% ../nbs/api/07_ratelimit.ipynb #69b0fb44
def client_ip(req, **kwargs):
    "Get client IP from `X-Forwarded-For` header, falling back to `req.client.host`"
    return req.headers.get('x-forwarded-for', '').split(',')[0].strip() or (req.client and req.client.host) or ''

# %% ../nbs/api/07_ratelimit.ipynb #75b5b395
class Limiter:
    "Rate limiter for FastHTML routes"
    def __init__(self, app):
        self._req_var = ContextVar('limiter_req')
        async def _store(req): self._req_var.set(req)
        app.before.insert(0, _store)

    def __call__(self,
                 rate:str|tuple,            # Rate string ('5/m') or (max_reqs, window_secs) tuple
                 key:str|Callable=client_ip, # Key to limit by: route param name, or callable(req, **kwargs)
                 on_limit:Callable=None     # Optional callback(wait_secs) to return custom response on 429
                ):
        "Rate limit decorator: `@limiter('5/m')`"
        bucket = TokenBucket(*rate) if isinstance(rate, tuple) else TokenBucket(rate)
        def decorator(f):
            @wraps(f)
            async def wrapper(*args, **kwargs):
                req = self._req_var.get()
                k = key(req, **kwargs) if callable(key) else str(kwargs.get(key, ''))
                if w:=bucket.wait(k):
                    if on_limit: return on_limit(w)
                    return Response('Too many requests', status_code=429, headers={'Retry-After': str(ceil(w))})
                return await maybe_await(f(*args, **kwargs))
            return wrapper
        return decorator
